const actionTypes = {
  GET_THE_COUNT_OF_NOTES_ASYNC: 'GET_THE_COUNT_OF_NOTES_ASYNC',
  SET_THE_COUNT_OF_NOTES: 'SET_THE_COUNT_OF_NOTES',
  SET_ERROR_MESSAGE_FOR_LIST_OF_NOTES: 'SET_ERROR_MESSAGE_FOR_LIST_OF_NOTES',
}

export default actionTypes
